apiVersion: v1
appVersion: "1.0"
description: Kubernetes application to build Bioconductor package binaries using the bioconductor_docker images on AKS
name: bioc-k8s-redis-aks
version: 3.13.0
maintainers:
  - name: Nitesh Turaga
