apiVersion: apps/v1
kind: Deployment
metadata:
  name: workcluster
  namespace: {{ .Values.clusterNamespace }}
  labels:
    tier: workcluster
spec:
  replicas: {{ .Values.workerPoolSize }}
  selector:
    matchLabels:
      tier: workcluster
  template:
    metadata:
      labels:
        tier: workcluster
    spec:
      containers:
      - name: worker
        image: {{ .Values.workerImage }}:{{ .Values.workerImageTag }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        resources:
          requests:
            memory: 1Gi
            cpu: 700m
          limits:
            memory: 4Gi
            cpu: 1.2
        volumeMounts:
         - name: {{ .Values.volumeMountName }}
           mountPath: {{ .Values.volumeMountPath }}
        command: ["R"]
        args: ["-f", "/home/docker/worker.R"]
      volumes:
      - name: {{ .Values.volumeMountName}}
        azureFile:
          secretName: {{ .Values.azFileShareSecret.secretName }}
          shareName: {{ .Values.azFileShareSecret.shareName }}
          readOnly: false
