apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: worker-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: worker
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
