# Default values for k8s-redis-bioc-chart. This is a YAML-formatted
# file. Declare variables to be passed into your templates.

version: 3.13.1

#
# user-oriented configuration
#

clusterNamespace: release
workerPoolSize: 50              # Number of workers in the cluster
dockerImageName: 'bioconductor_docker'  # Image name for which binaries are created
biocVersion: '3.12'
workerImageTag: RELEASE_3_12    # Needs to match the biocVersion

# Manager image
managerImage: bioconductor/bioc-redis
managerImageTag: az-manager

# Worker image
workerImage: bioconductor/bioc-redis

# Volume mount    
volumeMountName: azure ## azure
volumeMountPath: /host
volumeMountSize: 100Gi

# service key name
azFileShareSecret:
  secretName: azure-secret
  shareName: biocbinaries


# RStudio access
rstudioIngress:
  nodePort: 30001            # Port for user connection; must be >= 30000
  Password: bioc         # RStudio password on manager

#
# internal settings
#

# image management (manager, worker, redis)
pullPolicy: Always
restartPolicy: OnFailure

# internal RStudio-specific config
rstudio:
  port: 8787                    # RStudioServer configured to listen here
  protocol: http
  type: NodePort

# internal redis-specific config
redis:
  redisImage: redis
  redisImageTag: '5.0'
  containerPort: 6379
