apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile
spec:
  capacity:
    storage: {{ .Values.volumeMountSize }}
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: {{ .Values.azFileShareSecret.secretName }}
    shareName: {{ .Values.azFileShareSecret.shareName }}
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
