apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Release.Namespace}}-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.{{ .Release.Namespace }}.svc.cluster.local
    path: "/"
