apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-provisioning-demo
  labels:
    demo: nfs-pvc-provisioning
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
---
{{ if .Values.persistence.gcpPdName }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Release.Namespace}}-nfs-pv-provisioning-demo
  labels:
    demo: nfs-pv-provisioning
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes: [ "ReadWriteOnce" ]
  capacity:
    storage: {{ .Values.persistence.size }}
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: nfs-pvc-provisioning-demo
  gcePersistentDisk:
    pdName: {{ .Values.persistence.gcpPdName }}
    fsType: ext4
---
{{ end }}